export const searchNormalizeMap: Record<string, string> = {
  // Types
  top: "Tops",
  tops: "Tops",
  bottom: "Bottoms",
  bottoms: "Bottoms",
  pant: "Bottoms",
  pants: "Bottoms",
  outerwear: "Outerwear",
  dress: "Dresses",
  dresses: "Dresses",
  shoe: "Shoes",
  shoes: "Shoes",
  belt: "Belt",
  belts: "Belt",
  headwear: "Headwear",
  accessory: "Accessories",
  accessories: "Accessories",

  // Tops
  "t-shirt": "T-Shirt",
  tshirt: "T-Shirt",
  "t-shirts": "T-Shirt",
  tshirts: "T-Shirt",
  "long sleeve": "Long Sleeve Tee",
  "long sleeve tee": "Long Sleeve Tee",
  "long sleeves": "Long Sleeve Tee",
  "button down": "Button-Down",
  "button-down": "Button-Down",
  "button downs": "Button-Down",
  "button-downs": "Button-Down",
  blouse: "Blouse",
  blouses: "Blouse",
  sweater: "Sweater",
  sweaters: "Sweater",
  "tank top": "Tank Top",
  "tank tops": "Tank Top",
  tank: "Tank Top",
  tanks: "Tank Top",
  polo: "Polo",
  polos: "Polo",
  vest: "Vest",
  vests: "Vest",

  // Bottoms
  jean: "Jeans",
  jeans: "Jeans",
  denim: "Jeans",
  "dress pant": "Dress Pants",
  "dress pants": "Dress Pants",
  sweatpant: "Sweatpants",
  sweatpants: "Sweatpants",
  jogger: "Sweatpants",
  joggers: "Sweatpants",
  "cargo pant": "Cargo Pants",
  "cargo pants": "Cargo Pants",
  cargo: "Cargo Pants",
  cargos: "Cargo Pants",
  legging: "Leggings",
  leggings: "Leggings",
  short: "Shorts",
  shorts: "Shorts",
  "denim short": "Denim Shorts",
  "denim shorts": "Denim Shorts",
  jorts: "Denim Shorts",
  jort: "Denim Shorts",
  skirt: "Skirt",
  skirts: "Skirt",
  "mini skirt": "Mini Skirt",
  "mini skirts": "Mini Skirt",
  "midi skirt": "Midi Skirt",
  "midi skirts": "Midi Skirt",
  "maxi skirt": "Maxi Skirt",
  "maxi skirts": "Maxi Skirt",
  overall: "Overalls",
  overalls: "Overalls",

  // Outerwear
  hoodie: "Hoodie",
  hoodies: "Hoodie",
  jacket: "Jacket",
  jackets: "Jacket",
  coat: "Coat",
  coats: "Coat",
  puffer: "Puffer Jacket",
  "puffer jacket": "Puffer Jacket",
  "puffer jackets": "Puffer Jacket",
  blazer: "Blazer",
  blazers: "Blazer",
  bomber: "Bomber Jacket",
  "bomber jacket": "Bomber Jacket",
  "bomber jackets": "Bomber Jacket",
  "denim jacket": "Denim Jacket",
  "denim jackets": "Denim Jacket",
  raincoat: "Raincoat",
  raincoats: "Raincoat",
  fleece: "Fleece",
  windbreaker: "Windbreaker",
  windbreakers: "Windbreaker",
  "trench coat": "Trench Coat",
  "trench coats": "Trench Coat",
  trench: "Trench Coat",

  // Dresses
  "mini dress": "Mini Dress",
  "mini dresses": "Mini Dress",
  "midi dress": "Midi Dress",
  "midi dresses": "Midi Dress",
  "maxi dress": "Maxi Dress",
  "maxi dresses": "Maxi Dress",
  sundress: "Sundress",
  sundresses: "Sundress",
  "wrap dress": "Wrap Dress",
  "wrap dresses": "Wrap Dress",
  bodycon: "Bodycon Dress",
  "bodycon dress": "Bodycon Dress",
  "slip dress": "Slip Dress",
  "slip dresses": "Slip Dress",
  slip: "Slip Dress",
  romper: "Romper",
  rompers: "Romper",

  // Shoes
  sneaker: "Sneakers",
  sneakers: "Sneakers",
  "running shoe": "Running Shoes",
  "running shoes": "Running Shoes",
  boot: "Boots",
  boots: "Boots",
  loafer: "Loafers",
  loafers: "Loafers",
  "dress shoe": "Dress Shoes",
  "dress shoes": "Dress Shoes",
  sandal: "Sandals",
  sandals: "Sandals",
  slide: "Slides",
  slides: "Slides",
  heel: "Heels",
  heels: "Heels",
  flat: "Flats",
  flats: "Flats",
  mule: "Mules",
  mules: "Mules",

  // Belts
  "leather belt": "Leather Belt",
  "leather belts": "Leather Belt",
  "canvas belt": "Canvas Belt",
  "canvas belts": "Canvas Belt",
  "chain belt": "Chain Belt",
  "chain belts": "Chain Belt",
  "braided belt": "Braided Belt",
  "braided belts": "Braided Belt",

  // Headwear
  "baseball cap": "Baseball Cap",
  "baseball caps": "Baseball Cap",
  cap: "Baseball Cap",
  caps: "Baseball Cap",
  "fitted hat": "Fitted Hat",
  fitted: "Fitted Hat",
  beanie: "Beanie",
  beanies: "Beanie",
  "bucket hat": "Bucket Hat",
  "bucket hats": "Bucket Hat",
  snapback: "Snapback",
  snapbacks: "Snapback",
  beret: "Beret",
  berets: "Beret",
  fedora: "Fedora",
  fedoras: "Fedora",
  visor: "Visor",
  visors: "Visor",
  headband: "Headband",
  headbands: "Headband",
  hat: "Fitted Hat",
  hats: "Fitted Hat",

  // Accessories
  watch: "Watch",
  watches: "Watch",
  sunglass: "Sunglasses",
  sunglasses: "Sunglasses",
  necklace: "Necklace",
  necklaces: "Necklace",
  bracelet: "Bracelet",
  bracelets: "Bracelet",
  ring: "Ring",
  rings: "Ring",
  earring: "Earrings",
  earrings: "Earrings",
  scarf: "Scarf",
  scarfs: "Scarf",
  scarves: "Scarf",
  glove: "Gloves",
  gloves: "Gloves",
  bag: "Bag",
  bags: "Bag",
  purse: "Purse",
  backpack: "Backpack",
  backpacks: "Backpack",
  "tote bag": "Tote Bag",
  "tote bags": "Tote Bag",
  tote: "Tote Bag",
  totes: "Tote Bag",
  wallet: "Wallet",
  wallets: "Wallet",
  tie: "Tie",
  ties: "Tie",
  "bow tie": "Bow Tie",
  "bow ties": "Bow Tie",
  sock: "Socks",
  socks: "Socks",

  // Colors
  white: "White",
  black: "Black",
  grey: "Grey",
  gray: "Grey",
  khaki: "Khaki",
  brown: "Brown",
  blue: "Blue",
  green: "Green",
  red: "Red",
  pink: "Pink",
  yellow: "Yellow",
  orange: "Orange",
  purple: "Purple",
  silver: "Silver",
  gold: "Gold",
  multicolor: "Multicolor",
  multi: "Multicolor",
  multicolored: "Multicolor",
};

export const normalizeSearchTerm = (input: string): string => {
  return searchNormalizeMap[input.toLowerCase()] ?? input;
};
